### ISSUE TITLE
(Question) Volta architecture possible improvements

### ISSUE THREAD

**Issue by beevabeeva** [vincentfpgarcia/kNN-CUDA#8]
Hi Vincent (et al.),

Thank you for your contribution to the literature. I will probably be basing my implementation of KNN on your work, for my research. 

I just found the repo, and so I've not yet read your thesis.
I did read your note regarding GPGPU implementations being specific to the GPU(s) being used.

Do you think that the new Volta architecture offers any features that would merit a revised implementation? 

Any advice is welcomed.

Thank you!

**Comment by vincentfpgarcia** [comment]
Hi Beevabeeva,
This code was written in 2008. I assume GPU architecture changed quite a lot since that time.
Redesigning a better code for this new architecture will probably lead to faster results.
But I cannot be sure since I haven't investigated Volta (yet).
If you have time to spare, you'll probably learn a lot by investigating the Volta option.
I'm sorry that I'm not able to answer your question.
Best,
Vincent
